### REGISTRAZIONE
POST http://localhost:5000/api/auth/registrazione
Content-Type: application/json

{
  "email": "testing@drivedesk.it",
  "password": "test123",
  "ruolo": "Manager"
}

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "testing@drivedesk.it",
  "password": "test123"
}

### CREA VEICOLO (token)
POST http://localhost:5000/api/veicoli
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjk3YmVhMmJhZTFjNjg2ODk4YTZiNzg5IiwicnVvbG8iOiJNYW5hZ2VyIn0sImlhdCI6MTc3MDU0MTg2OSwiZXhwIjoxNzcwOTAxODY5fQ.mHM3C47HrrX3djbLSkk5iqdZPsex-aiCBjtE7pvPqL0

{
  "targa": "XZ 904 HP",
  "nomeAutista": "Davide Montesi",
  "numeroAutista": "3516674820",
  "stato": "sosta",
  "posizione": "35.72, 27.58"
}

### SIMULAZIONE SENSORE (Telemetria + Guasto)
POST http://localhost:5000/api/telemetria
Content-Type: application/json

{
  "targa": "AT 118 ZH",
  "posizione": "95.72, 27.58",
  "velocita": 88,
  "livelloCarburante": 40,
  "guasto": "surriscaldamento"
}
